@startuml
'https://plantuml.com/class-diagram

entity Seller {
    * username <<pk>>
    * password
}

entity Product {
    * product_id <<pk>>
    * seller_username <<fk>>
    * name
    * description
    * price
    image
}

entity Line_item {
    * cart_item_id <<pk>>
    * product_id <<fk>>
    * quantity
    * price
}

entity Cart {
    * cart_id <<pk>>
}

entity Order {
    * order_id <<pk>>
    * buyer_name
    * buyer_email
    * address
    * payment_info
}


@enduml