@startuml
'https://plantuml.com/class-diagram

entity Seller {
    * username
    --
    * password
}

entity Product {
    * name
    --
    * description
    * price
    image
}

entity Cart_item {
    * quantity
    * price
    --
}

entity Cart {
}

entity Order {
    * order_id
    --
    * buyer_name
    * buyer_email
    * address
    * payment_info
}

Seller }o--|| Product
Product }o--|| Cart_item
Cart_item }o--o{ Cart
Cart_item }o--o{ Order

@enduml